"use client";
import { useMemo, useState } from "react";
import { useCloseShift, useCurrentShift, useOpenShift, useShiftReport } from "@/services/shift/shift.queries";
import { formatVnd } from "@/utils/format";

const money = (value: number | null | undefined) => formatVnd(value ?? 0);
export function ShiftWorkspace({ title = "Chốt ca & đối soát" }: { title?: string }) {
  const current = useCurrentShift(); const report = useShiftReport(); const open = useOpenShift(); const close = useCloseShift();
  const [opening, setOpening] = useState("0"); const [counted, setCounted] = useState(""); const [note, setNote] = useState("");
  const shift = current.data; const summary = report.data?.summary;
  const expected = shift?.openingCash !== undefined ? (summary?.cash ?? 0) + (shift?.openingCash ?? 0) : 0;
  const variance = counted === "" ? null : Number(counted) - expected;
  const csv = useMemo(() => {
    if (!report.data) return "";
    const rows = [["Thời điểm", "Phương thức", "Nguồn", "Tổng tiền"], ...report.data.transactions.map((t) => [new Date(t.paidAt).toLocaleString("vi-VN"), t.method, t.source, String(t.totalAmount)])];
    return "\\ufeff" + rows.map((r) => r.join(",")).join("\\n");
  }, [report.data]);
  const downloadCsv = () => { const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "chalo-doi-soat.csv"; a.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-5 p-4 sm:p-6"><header><h1 className="text-xl font-bold text-gray-900 dark:text-gray-100">{title}</h1><p className="text-sm text-gray-500">Quỹ tiền mặt chung · VND</p></header>
    {!shift ? <section className="rounded-2xl border bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-900"><h2 className="font-semibold">Chưa có ca mở</h2><p className="mt-1 text-sm text-gray-500">Thanh toán vẫn hoạt động, nhưng chưa được tính vào tiền dự kiến.</p><div className="mt-4 flex gap-2"><input aria-label="Tiền đầu ca" inputMode="numeric" value={opening} onChange={(e) => setOpening(e.target.value.replace(/\\D/g, ""))} className="min-h-11 min-w-0 flex-1 rounded-xl border px-3 dark:border-gray-700 dark:bg-gray-800" placeholder="Tiền đầu ca" /><button className="min-h-11 rounded-xl bg-brand-500 px-4 font-bold text-white" onClick={() => open.mutate(Number(opening) || 0)}>Mở ca</button></div></section> : <section className="rounded-2xl border border-brand-200 bg-brand-50 p-4 dark:border-brand-900/50 dark:bg-brand-950/20"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-brand-700 dark:text-brand-300">Ca đang mở</p><p className="text-lg font-bold text-brand-900 dark:text-brand-100">Từ {new Date(shift.openedAt).toLocaleString("vi-VN")}</p></div><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-700">OPEN</span></div><div className="mt-4 grid grid-cols-2 gap-3"><div><p className="text-xs text-gray-500">Tiền đầu ca</p><p className="font-bold">{money(shift.openingCash)}</p></div><div><p className="text-xs text-gray-500">Tiền mặt dự kiến</p><p className="font-bold">{money(expected)}</p></div></div><div className="mt-4 space-y-2"><input aria-label="Tiền thực đếm" inputMode="numeric" value={counted} onChange={(e) => setCounted(e.target.value.replace(/\\D/g, ""))} className="min-h-11 w-full rounded-xl border px-3 dark:border-gray-700 dark:bg-gray-800" placeholder="Nhập tiền thực đếm" /><input aria-label="Ghi chú chốt ca" value={note} onChange={(e) => setNote(e.target.value)} className="min-h-11 w-full rounded-xl border px-3 dark:border-gray-700 dark:bg-gray-800" placeholder="Ghi chú nếu lệch" />{variance !== null ? <p className={`rounded-xl p-3 text-sm font-semibold ${variance === 0 ? "bg-green-100 text-green-700" : "bg-amber-100 text-amber-800"}`}>Chênh lệch: {money(variance)}</p> : null}<button disabled={counted === "" || (variance !== 0 && !note.trim()) || close.isPending} className="min-h-11 w-full rounded-xl bg-red-500 px-4 font-bold text-white disabled:opacity-50" onClick={() => close.mutate({ countedCash: Number(counted), note })}>Chốt ca</button></div></section>}
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Doanh thu đã thu", summary?.paidRevenue], ["Tiền mặt", summary?.cash], ["Chuyển khoản", summary?.bankTransfer], ["Đơn chưa trả", summary?.unpaidOrders]].map(([label, value]) => <div key={label} className="rounded-2xl border bg-white p-4 dark:border-gray-800 dark:bg-gray-900"><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-lg font-bold">{typeof value === "number" ? money(value) : "—"}</p></div>)}</section>
    <section className="rounded-2xl border bg-white p-4 dark:border-gray-800 dark:bg-gray-900"><div className="flex items-center justify-between"><h2 className="font-semibold">Giao dịch gần đây</h2><button disabled={!csv} onClick={downloadCsv} className="min-h-11 rounded-xl border px-3 text-sm font-semibold disabled:opacity-40">Tải CSV</button></div><div className="mt-3 space-y-2">{(report.data?.transactions ?? []).slice(0, 8).map((t) => <div key={t.id} className="flex items-center justify-between gap-3 rounded-xl bg-gray-50 p-3 text-sm dark:bg-gray-800"><div><p className="font-semibold">{t.method === "CASH" ? "Tiền mặt" : t.method === "BANK_TRANSFER" ? "QR chuyển khoản" : "Legacy"}</p><p className="text-xs text-gray-500">{new Date(t.paidAt).toLocaleString("vi-VN")}</p></div><span className="font-bold">{money(t.totalAmount)}</span></div>)}</div></section>
  </div>;
}
