"use client";
import { OrderDto, OrderStatus } from "@/services/order/order.types";
import { useState } from "react";
import { KANBAN_COLUMNS, orderDragType } from "./orders.config";
import { OrderCard } from "./OrderCard";
export function KanbanColumn({ config, orders, onStatusChange, updatingId, detailHref }: { config: (typeof KANBAN_COLUMNS)[number]; orders: OrderDto[]; onStatusChange: (orderId: string, status: OrderStatus) => void; updatingId: string | null; detailHref: (id: string) => string }) {
  const [drop, setDrop] = useState(false); const accepts = (e: React.DragEvent) => e.dataTransfer.types.includes(orderDragType(config.status));
  return <div className="flex min-w-[220px] flex-1 flex-col" onDragOver={(e) => { if (!accepts(e)) return; e.preventDefault(); e.dataTransfer.dropEffect = "move"; setDrop(true); }} onDragLeave={(e) => { if (!e.currentTarget.contains(e.relatedTarget as Node)) setDrop(false); }} onDrop={(e) => { setDrop(false); if (!accepts(e)) return; e.preventDefault(); const id = e.dataTransfer.getData("text/plain"); if (id) onStatusChange(id, config.status); }}><div className={`flex items-center justify-between px-3 py-2.5 rounded-t-xl border ${config.bgColor} ${config.borderColor}`}><div className="flex items-center gap-2"><span>{config.emoji}</span><span className={`text-sm font-bold ${config.textColor}`}>{config.label}</span></div>{orders.length > 0 && <span className={`size-5 rounded-full text-xs font-bold flex items-center justify-center ${config.bgColor} ${config.textColor} border ${config.borderColor}`}>{orders.length}</span>}</div><div className={`flex-1 min-h-[120px] border-x border-b ${config.borderColor} dark:bg-stone-900 rounded-b-xl p-2 space-y-2 overflow-y-auto ${drop ? "ring-2 ring-inset ring-brand-400" : ""}`}>{orders.length === 0 ? <p className="text-xs text-stone-400 text-center py-6">Không có đơn</p> : orders.map((order) => <OrderCard key={order.id} order={order} isUpdating={updatingId === order.id} onStatusChange={onStatusChange} detailHref={detailHref} />)}</div></div>;
}
