"use client";
import { SpinnerIcon } from "@/components/shared/icons/SpinnerIcon";
import { OrderDto, OrderStatus } from "@/services/order/order.types";
import { useMemo, useState } from "react";
import { KANBAN_COLUMNS, KHACH_DAT_STATUSES } from "./orders.config";
import { KanbanColumn } from "./KanbanColumn";

const normalize = (s: string) => s.normalize("NFD").replace(/\p{M}/gu, "").replace(/đ/gi, "d").toLowerCase();
export function OrderOperationsBoard({ orders, isLoading, isLive, onRefresh, onStatusChange, detailHref, prepDockToggle }: { orders?: OrderDto[]; isLoading: boolean; isLive: boolean; onRefresh: () => void; onStatusChange: (orderId: string, status: OrderStatus) => void; detailHref: (id: string) => string; prepDockToggle?: React.ReactNode }) {
  const [search, setSearch] = useState(""); const [mobileStatus, setMobileStatus] = useState<OrderStatus>("PENDING"); const [updatingId, setUpdatingId] = useState<string | null>(null);
  const filtered = useMemo(() => { const q = normalize(search.trim()); const all = (orders ?? []).filter((o) => !q || normalize(o.tableName ?? "").includes(q)); return (status: OrderStatus) => status === "PENDING" ? all.filter((o) => KHACH_DAT_STATUSES.includes(o.status)) : status === "COMPLETED" ? all.filter((o) => o.status === "COMPLETED" && !o.paidStatus) : all.filter((o) => o.status === status); }, [orders, search]);
  const change = async (id: string, status: OrderStatus) => { setUpdatingId(id); try { await onStatusChange(id, status); } finally { setUpdatingId(null); } };
  return <div className="h-full flex flex-col"><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 md:px-6 md:py-4 border-b border-gray-200 bg-white dark:bg-gray-900 shrink-0"><div><h1 className="text-lg font-bold text-gray-900 dark:text-gray-100">Đơn hàng</h1><p className="text-sm text-gray-500">Real-time · {(orders ?? []).length} đơn đang xử lý</p></div><div className="flex w-full items-center gap-2 sm:w-auto"><input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="🔍 Tìm bàn..." className="min-w-0 flex-1 rounded-lg border border-gray-200 px-3 py-2 text-sm sm:w-44 sm:flex-none" /><div className="flex items-center gap-1.5 text-xs text-green-600"><span className={`size-2 rounded-full ${isLive ? "bg-green-500 animate-pulse" : "bg-gray-400"}`} />{isLive ? "Live" : "Connecting..."}</div>{prepDockToggle}<button onClick={onRefresh} className="min-h-10 shrink-0 rounded-lg border border-gray-200 px-3 py-1.5 text-sm">🔄 Làm mới</button></div></div>{isLoading ? <div className="flex-1 flex items-center justify-center"><SpinnerIcon className="size-8 animate-spin text-brand-400" /></div> : <><div className="flex shrink-0 gap-1 overflow-x-auto border-b p-2 md:hidden">{KANBAN_COLUMNS.map((c) => <button key={c.status} type="button" onClick={() => setMobileStatus(c.status)} className={`min-h-11 shrink-0 rounded-xl px-3 text-sm font-semibold ${mobileStatus === c.status ? "bg-brand-50 text-brand-700" : "text-gray-500"}`}>{c.emoji} {c.label} {filtered(c.status).length ? `(${filtered(c.status).length})` : ""}</button>)}</div><div className="flex-1 min-h-0 p-3 md:hidden">{KANBAN_COLUMNS.filter((c) => c.status === mobileStatus).map((c) => <KanbanColumn key={c.status} config={c} orders={filtered(c.status)} onStatusChange={change} updatingId={updatingId} detailHref={detailHref} />)}</div><div className="relative hidden min-h-0 flex-1 overflow-x-auto p-4 md:block"><div className="flex gap-3 h-full min-w-[680px]">{KANBAN_COLUMNS.map((c) => <KanbanColumn key={c.status} config={c} orders={filtered(c.status)} onStatusChange={change} updatingId={updatingId} detailHref={detailHref} />)}</div></div></>}</div>;
}
