"use client";
import { ProductFormType } from "@/schemas/menu.schema";
import { useFieldArray, UseFormRegister, UseFormSetValue, Control } from "react-hook-form";

export function ProductModifierFields({ control, register, setValue }: { control: Control<ProductFormType>; register: UseFormRegister<ProductFormType>; setValue: UseFormSetValue<ProductFormType> }) {
  const groups = useFieldArray({ control, name: "modifierGroups" });
  return <section data-testid="product-edit-section-modifiers" className="rounded-2xl border border-gray-100 bg-gray-50/70 p-3 dark:border-gray-800 dark:bg-gray-950/40 sm:rounded-none sm:border-0 sm:bg-transparent sm:p-0">
    <div className="mb-3 flex items-center justify-between gap-3"><div><h3 className="text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400">Tùy chọn món</h3><p className="mt-1 text-xs text-gray-400">Tạo riêng cho món này; lựa chọn mới mặc định cộng 0đ.</p></div><button type="button" onClick={() => groups.append({ name: "", selectionType: "SINGLE", isRequired: false, sortOrder: groups.fields.length, options: [{ name: "", priceAdjustment: 0, sortOrder: 0 }] })} className="min-h-10 rounded-xl border border-brand-200 bg-white px-3 text-xs font-semibold text-brand-700 hover:bg-brand-50 dark:bg-gray-800 dark:text-brand-300">+ Thêm nhóm</button></div>
    <div className="space-y-3">{groups.fields.map((group, index) => <ModifierGroup key={group.id} index={index} control={control} register={register} setValue={setValue} onRemove={() => groups.remove(index)} />)}</div>
  </section>;
}

function ModifierGroup({ index, control, register, setValue, onRemove }: { index: number; control: Control<ProductFormType>; register: UseFormRegister<ProductFormType>; setValue: UseFormSetValue<ProductFormType>; onRemove: () => void }) {
  const options = useFieldArray({ control, name: `modifierGroups.${index}.options` });
  return <div className="rounded-xl border border-gray-200 bg-white p-3 dark:border-gray-700 dark:bg-gray-800"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-2"><input {...register(`modifierGroups.${index}.name`)} aria-label={`Tên nhóm tùy chọn ${index + 1}`} placeholder="VD: Size, Đá, Đường..." className="min-h-10 rounded-lg border border-gray-200 bg-transparent px-3 text-sm dark:border-gray-600"/><button type="button" onClick={onRemove} aria-label={`Xóa nhóm tùy chọn ${index + 1}`} className="min-h-10 rounded-lg px-2 text-xs font-medium text-red-500 hover:bg-red-50">Xóa</button></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-2 text-xs text-gray-600 dark:text-gray-300"><label><input type="radio" value="SINGLE" {...register(`modifierGroups.${index}.selectionType`)} /> Chọn một</label><label><input type="radio" value="MULTIPLE" {...register(`modifierGroups.${index}.selectionType`)} /> Chọn nhiều</label><label><input type="checkbox" {...register(`modifierGroups.${index}.isRequired`)} /> Bắt buộc</label></div><div className="mt-3 space-y-2">{options.fields.map((option, optionIndex) => <div key={option.id} className="grid grid-cols-[minmax(0,1fr)_5.5rem_auto] gap-2"><input {...register(`modifierGroups.${index}.options.${optionIndex}.name`)} aria-label={`Lựa chọn ${optionIndex + 1} nhóm ${index + 1}`} placeholder="Tên lựa chọn" className="min-h-10 rounded-lg border border-gray-200 bg-transparent px-3 text-sm dark:border-gray-600"/><input {...register(`modifierGroups.${index}.options.${optionIndex}.priceAdjustment`)} type="number" min="0" step="1000" aria-label={`Phụ thu lựa chọn ${optionIndex + 1} nhóm ${index + 1}`} className="min-h-10 rounded-lg border border-gray-200 bg-transparent px-2 text-sm dark:border-gray-600"/><button type="button" onClick={() => options.remove(optionIndex)} aria-label={`Xóa lựa chọn ${optionIndex + 1} nhóm ${index + 1}`} className="min-h-10 rounded-lg px-2 text-xs text-red-500">×</button></div>)}<button type="button" onClick={() => options.append({ name: "", priceAdjustment: 0, sortOrder: options.fields.length })} className="min-h-10 text-left text-xs font-semibold text-brand-700">+ Thêm lựa chọn (0đ)</button></div></div>;
}
