// src/constants/api-endpoints.ts

export const API = {
  AUTH: {
    LOGIN: "/auth/login",
    GOOGLE_EXCHANGE: "/auth/google/exchange",
    REGISTER: "/auth/register",
    REFRESH: "/auth/refresh-token",
    LOGOUT: "/auth/logout",
    ME: "/auth/me",
  },
  CUSTOMER: {
    ME: "/customer/me",
    TABLE_SESSION: "/customer/table-session",
    SCAN_TABLE: "/customer/table-session/scan",
    LEAVE_TABLE: "/customer/table-session/leave",
    LOYALTY: "/customer/loyalty",
    ORDERS: "/customer/orders",
  },
  USER: {
    PAGE: "/user/page",
    CREATE: "/user/create",
    UPDATE: "/user/update",
    CHANGE_PASSWORD: "/user/change-password",
    DELETE: "/user/delete",
    CUSTOMER_ORDERS: (id: number) => `/user/${id}/orders`,
    CUSTOMER_LOYALTY: (id: number) => `/user/${id}/loyalty`,
    SET_ACTIVE: (id: number) => `/user/${id}/active`,
  },
  CATEGORY: {
    LIST: "/menu/category/list",
    SIMPLE_LIST: "/menu/category/simple-list",
    DETAIL: "/menu/category/detail",
    CREATE: "/menu/category/create",
    UPDATE: "/menu/category/update",
    DELETE: "/menu/category/delete",
  },
  PRODUCT: {
    LIST: "/menu/product/list",
    PAGE: "/menu/product/page",
    DETAIL: "/menu/product/detail",
    SIMPLE_LIST: "/menu/product/simple-list",
    CREATE: "/menu/product/create",
    UPDATE: "/menu/product/update",
    UPDATE_STATUS: "/menu/product/status",
    DELETE: "/menu/product/delete",
  },
  TABLE: {
    PAGE: "/table/page",
    LIST: "/table/list",
    BY_TOKEN: "/table/by-token",
    AREAS: "/table/areas",
    CREATE: "/table/create",
    UPDATE: "/table/update",
    DELETE: "/table/delete",
    REGENERATE_QR: "/table/regenerate-qr",
  },
  ORDER: {
    CREATE: "/order/create",
    PAGE: "/order/page",
    ACTIVE: "/order/active",
    DETAIL: "/order/detail",
    BY_TOKEN: "/order/by-token",
    ESTIMATED_WAIT: "/order/estimated-wait",
    UPDATE_STATUS: "/order/status",
    DELETE: (id: string) => `/order/${id}`,
    ITEM_PREPARED: (itemId: string) => `/order/item/${itemId}/prepared`,
    REQUEST_PAYMENT: "/order/request-payment",
    PAY: "/order/pay",
    PAY_ALL: "/order/pay-all",
    CALL_STAFF: "/order/call-staff",
    CHECKOUT_PREVIEW: "/order/checkout/preview",
    CHECKOUT_START: "/order/checkout/start",
    STATS_REVENUE: "/order/stats/revenue",
    STATS_TOP_PRODUCTS: "/order/stats/top-products",
  },
  PAGER: {
    LIST: "/pager/list",
    ASSIGN: "/pager/assign",
    CALL: "/pager/call",
    RELEASE: "/pager/release",
  },
  SETTINGS: {
    GET: "/settings",
    UPDATE: "/settings",
  },
  SHIFT: { CURRENT: "/shift/current", OPEN: "/shift/open", CLOSE: "/shift/current/close", REPORT: "/shift/report" },
  UPLOAD: {
    IMAGE: "/upload/image",
  },
  SSE: {
    ORDER_EVENTS: "/order/events",
    ORDER_EVENTS_BY_TABLE: "/order/events/by-table",
  },
  HEALTH: {
    CHECK: "/health",
  },
} as const;
